#!/bin/bash
# Quick Gmail Unlock Script

echo "=================================="
echo "🔓 Gmail Account Unlock Process"
echo "=================================="
echo ""
echo "Step 1: Open this link in your browser:"
echo "👉 https://accounts.google.com/DisplayUnlockCaptcha"
echo ""
echo "Step 2: Login with: imdadkhanr9@gmail.com"
echo ""
echo "Step 3: Click 'Continue' button"
echo ""
echo "Step 4: Wait 10 minutes for Gmail to reset"
echo ""
echo "=================================="
echo "📝 What We Fixed:"
echo "=================================="
echo "✅ CRON job changed from every minute to once daily"
echo "✅ This prevents Gmail blocking"
echo "✅ OTP emails will now work properly"
echo ""
echo "=================================="
echo "🔄 Next Steps:"
echo "=================================="
echo "1. Unlock Gmail using the link above"
echo "2. Wait 10 minutes"
echo "3. Restart backend server"
echo "4. Test OTP from frontend"
echo ""
echo "=================================="
